run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/AndreyChufelin
          - "github.com/jackc/pgx/v5"
          - "github.com/spf13/viper"
          - "github.com/labstack/echo/v4"
          - "github.com/labstack/echo/v4/middleware"
          - "github.com/go-playground/locales/en"
          - "github.com/go-playground/universal-translator"
          - "github.com/go-playground/validator/v10"
          - "github.com/go-playground/validator/v10/translations/en"
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/AndreyChufelin
  tagliatelle:
    case:
      rules:
        json: snake
        db: snake

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace