[db]
user = "postgres"
password = "postgres"
name = "postgres"
host = "localhost"
port = "5432"
max_open_conns = 25
max_idle_conns = 25
max_idle_time = "15m"
[mailer]
host = "localhost"
port = 1025
sender = "movies@example.com"