// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/pb/UserService.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Activated     bool                   `protobuf:"varint,4,opt,name=activated,proto3" json:"activated,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_pkg_pb_UserService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_UserService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_pkg_pb_UserService_proto_rawDescGZIP(), []int{0}
}

func (x *UserMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserMessage) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *UserMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_pb_UserService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_UserService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_UserService_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ActivatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivatedRequest) Reset() {
	*x = ActivatedRequest{}
	mi := &file_pkg_pb_UserService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatedRequest) ProtoMessage() {}

func (x *ActivatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_UserService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatedRequest.ProtoReflect.Descriptor instead.
func (*ActivatedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_UserService_proto_rawDescGZIP(), []int{2}
}

func (x *ActivatedRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pkg_pb_UserService_proto protoreflect.FileDescriptor

const file_pkg_pb_UserService_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/pb/UserService.proto\x12\x04user\"\x84\x01\n" +
	"\vUserMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\tactivated\x18\x04 \x01(\bR\tactivated\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"W\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"(\n" +
	"\x10ActivatedRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2{\n" +
	"\vUserService\x124\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x11.user.UserMessage\x126\n" +
	"\tActivated\x12\x16.user.ActivatedRequest\x1a\x11.user.UserMessageB3Z1github.com/AndreyChufelin/movies-auth/pkg/pb/userb\x06proto3"

var (
	file_pkg_pb_UserService_proto_rawDescOnce sync.Once
	file_pkg_pb_UserService_proto_rawDescData []byte
)

func file_pkg_pb_UserService_proto_rawDescGZIP() []byte {
	file_pkg_pb_UserService_proto_rawDescOnce.Do(func() {
		file_pkg_pb_UserService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_UserService_proto_rawDesc), len(file_pkg_pb_UserService_proto_rawDesc)))
	})
	return file_pkg_pb_UserService_proto_rawDescData
}

var file_pkg_pb_UserService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_pb_UserService_proto_goTypes = []any{
	(*UserMessage)(nil),      // 0: user.UserMessage
	(*RegisterRequest)(nil),  // 1: user.RegisterRequest
	(*ActivatedRequest)(nil), // 2: user.ActivatedRequest
}
var file_pkg_pb_UserService_proto_depIdxs = []int32{
	1, // 0: user.UserService.Register:input_type -> user.RegisterRequest
	2, // 1: user.UserService.Activated:input_type -> user.ActivatedRequest
	0, // 2: user.UserService.Register:output_type -> user.UserMessage
	0, // 3: user.UserService.Activated:output_type -> user.UserMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_UserService_proto_init() }
func file_pkg_pb_UserService_proto_init() {
	if File_pkg_pb_UserService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_UserService_proto_rawDesc), len(file_pkg_pb_UserService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_UserService_proto_goTypes,
		DependencyIndexes: file_pkg_pb_UserService_proto_depIdxs,
		MessageInfos:      file_pkg_pb_UserService_proto_msgTypes,
	}.Build()
	File_pkg_pb_UserService_proto = out.File
	file_pkg_pb_UserService_proto_goTypes = nil
	file_pkg_pb_UserService_proto_depIdxs = nil
}
